// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa4LC3O9Vv5K0uuX6u3pGrP2FYVBoS6vw',
    appId: '1:328299742075:web:454d1070d208cbc4ba73de',
    messagingSenderId: '328299742075',
    projectId: 'marcet-7d273',
    authDomain: 'marcet-7d273.firebaseapp.com',
    databaseURL: 'https://marcet-7d273-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcet-7d273.appspot.com',
    measurementId: 'G-MWMQ7KD832',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRLbd7kHx9T_5T2Re6uxwOqAytssB6ug',
    appId: '1:328299742075:android:bb2f19cb0957508aba73de',
    messagingSenderId: '328299742075',
    projectId: 'marcet-7d273',
    databaseURL: 'https://marcet-7d273-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcet-7d273.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF2z73JE_izd13eFHre53iQimQ4UJaW_0',
    appId: '1:328299742075:ios:50f92a15edbdb906ba73de',
    messagingSenderId: '328299742075',
    projectId: 'marcet-7d273',
    databaseURL: 'https://marcet-7d273-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcet-7d273.appspot.com',
    iosBundleId: 'com.example.raed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF2z73JE_izd13eFHre53iQimQ4UJaW_0',
    appId: '1:328299742075:ios:26103f74fa18fb53ba73de',
    messagingSenderId: '328299742075',
    projectId: 'marcet-7d273',
    databaseURL: 'https://marcet-7d273-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'marcet-7d273.appspot.com',
    iosBundleId: 'com.example.raed.RunnerTests',
  );
}
